[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "https://magazine.ravereviewz.net/*"
  to = "https://www.ravereviewz.net/:splat"
[[redirects]]
  from = "https://www.ravereviewz.net.au/*"
  to = "https://www.ravereviewz.net/:splat"
[[redirects]]
  from = "https://ravereviewz.net/*"
  to = "https://www.ravereviewz.net/:splat"
[[redirects]]
  from = "/events"
  to = "/Events-Location/Sydney/"
[[redirects]]
  from = "/Events-Location/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/Events-Location/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/Event/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/PromotorList/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/PromotorList/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/VenueList/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/VenueList"
  status = 200
  force = true
[[redirects]]
  from = "/promotorvenue-faqs/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/what-the-faq/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/css/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/scripts/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/Content/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/umbraco/*"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/umbraco/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/jquery-2.1.4.min.js"
  to = "http://ravereviewz-286156834.ap-southeast-2.elb.amazonaws.com/jquery-2.1.4.min.js"
  status = 200
  force = true
