backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "interviews"
    label: "Interviews"
    folder: "src/pages/interviews"
    create: true
    slug: "/interview/{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "interview-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
  - name: "reviews"
    label: "Reviews"
    folder: "src/pages/reviews"
    create: true
    slug: "/review/{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "review-post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
  - name: "community"
    label: "Community"
    folder: "src/pages/community"
    create: true
    slug: "/community/{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "community-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Link", name: "link", widget: "string"}
  - name: "podcasts"
    label: "Podcasts"
    folder: "src/pages/podcasts"
    create: true
    slug: "/podcasts/{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "podcasts-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"}
      - {label: "Link", name: "link", widget: "string"}
  
  # - name: "pages"
  #   label: "Pages"
  #   files:
  #     - file: "src/pages/about-us/about-us.md"
  #       label: "About Us"
  #       name: "about-is"
  #       fields:
  #         - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
  #         - {label: "Path", name: "path", widget: "hidden", default: "/about"}
  #         - {label: "Title", name: "title", widget: "string"}
  #         - {label: "Body", name: "body", widget: "markdown"}

          